services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beautybloom-backend
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: beautybloom-frontend
    ports:
      - "8080:80"